//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WS.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanners were found!.
        /// </summary>
        internal static string E_NO_SCANNER_FOUND {
            get {
                return ResourceManager.GetString("E_NO_SCANNER_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        internal static string L_CROP_ZONE_H {
            get {
                return ResourceManager.GetString("L_CROP_ZONE_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop area.
        /// </summary>
        internal static string L_CROP_ZONE_MOUSE_LABEL {
            get {
                return ResourceManager.GetString("L_CROP_ZONE_MOUSE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string L_CROP_ZONE_MOUSE_UNITS_CM {
            get {
                return ResourceManager.GetString("L_CROP_ZONE_MOUSE_UNITS_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set crop area (cm):.
        /// </summary>
        internal static string L_CROP_ZONE_SET {
            get {
                return ResourceManager.GetString("L_CROP_ZONE_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        internal static string L_CROP_ZONE_W {
            get {
                return ResourceManager.GetString("L_CROP_ZONE_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left:.
        /// </summary>
        internal static string L_CROP_ZONE_X {
            get {
                return ResourceManager.GetString("L_CROP_ZONE_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top:.
        /// </summary>
        internal static string L_CROP_ZONE_Y {
            get {
                return ResourceManager.GetString("L_CROP_ZONE_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string L_INITIALIZING {
            get {
                return ResourceManager.GetString("L_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image\nis not scanned yet..
        /// </summary>
        internal static string L_NO_PREVIEW_IMAGE {
            get {
                return ResourceManager.GetString("L_NO_PREVIEW_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string L_READY {
            get {
                return ResourceManager.GetString("L_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan and save to file.
        /// </summary>
        internal static string L_SCAN_FULL_QUALITY {
            get {
                return ResourceManager.GetString("L_SCAN_FULL_QUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scanning:.
        /// </summary>
        internal static string L_SCAN_FULL_QUALITY_GRP {
            get {
                return ResourceManager.GetString("L_SCAN_FULL_QUALITY_GRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual scanning multiple pages.
        /// </summary>
        internal static string L_SCAN_FULL_QUALITY_MANUAL {
            get {
                return ResourceManager.GetString("L_SCAN_FULL_QUALITY_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan using OS system UI.
        /// </summary>
        internal static string L_SCAN_FULL_QUALITY_USING_OS_UI {
            get {
                return ResourceManager.GetString("L_SCAN_FULL_QUALITY_USING_OS_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan parameters:.
        /// </summary>
        internal static string L_SCAN_PARAMS {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Sides.
        /// </summary>
        internal static string L_SCAN_PARAMS_AUTOFEEDER_DOUBLE_SIDE {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_AUTOFEEDER_DOUBLE_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Autofeeder.
        /// </summary>
        internal static string L_SCAN_PARAMS_AUTOFEEDER_USE {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_AUTOFEEDER_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resolution:.
        /// </summary>
        internal static string L_SCAN_PARAMS_DPI {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_DPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save files to:.
        /// </summary>
        internal static string L_SCAN_PARAMS_FILE_DIR {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_FILE_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string L_SCAN_PARAMS_FILE_FORMAT {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality (%):.
        /// </summary>
        internal static string L_SCAN_PARAMS_FILE_QUALITY {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_FILE_QUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string L_SCAN_PARAMS_FILE_SELECT {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_FILE_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        internal static string L_SCAN_PARAMS_MODE {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black-white text.
        /// </summary>
        internal static string L_SCAN_PARAMS_MODE_BW_TEXT {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_MODE_BW_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color image.
        /// </summary>
        internal static string L_SCAN_PARAMS_MODE_COLOR_IMAGE {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_MODE_COLOR_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscaled.
        /// </summary>
        internal static string L_SCAN_PARAMS_MODE_GRAYSCALE {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_MODE_GRAYSCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner:.
        /// </summary>
        internal static string L_SCAN_PARAMS_SCANNER {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_SCANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page: {0}cm..
        /// </summary>
        internal static string L_SCAN_PARAMS_SCANNER_PAGE_SIZE {
            get {
                return ResourceManager.GetString("L_SCAN_PARAMS_SCANNER_PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Preview Scan.
        /// </summary>
        internal static string L_SCAN_PREVIEW {
            get {
                return ResourceManager.GetString("L_SCAN_PREVIEW", resourceCulture);
            }
        }
    }
}
